# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[('PENDING', 0), ('SUCCEEDED', 1), ('FAILED', 2)], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
