# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20160930_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeteaseUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('picture', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
